FROM mcr.microsoft.com/dotnet/aspnet:9.0  AS base
COPY bin/Release/net9.0/publish/ app/
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
RUN dotnet dev-certs https -v -ep openiddict.pfx -p 9a3a427b-1eb4-42ad-a4d8-96b9d328c4c2

FROM base AS final
WORKDIR /app
COPY --from=build /src .

ENTRYPOINT ["dotnet", "Ecommerce.HttpApi.Host.dll"]